version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: terminalx
    ports:
      - '5432:5432'
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  api:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev --workspace @terminal-x/api"
    environment:
      - NODE_ENV=development
    ports:
      - '4000:4000'
    depends_on:
      - db
      - redis
  bot:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev --workspace @terminal-x/bot"
    depends_on:
      - db
      - redis
  web:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev --workspace @terminal-x/web"
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    depends_on:
      - api
